Islandora-CLAW/islandora

README.md
islandora/README.md

Addresses islandora-claw/CLAW#312

Update references ot Danny's GitHub account

---

LICENSE

See: https://github.com/Islandora-CLAW/CLAW/issues/409
@DiegoPino should merge this since he had the commit on the other LICENSE file.

Use the correct LICENSE.

---

config/install/islandora.settings.yml
islandora.links.menu.yml
islandora.routing.yml
src/Form/IslandoraSettingsForm.php

Addresses https://github.com/Islandora-CLAW/CLAW/issues/393

Add basic config form for Islandora

---

islandora/config/install/rdf.mapping.fedora_resource_type.rdf_source.yml
islandora/src/Entity/FedoraResource.php

Resolves https://github.com/Islandora-CLAW/CLAW/issues/442
Check this first, I didn't map every possible field. Which I can if we want. Also there is **no** default mapping for a Non RDF Source. I can add that to this, or we should create another ticket.

Add RDF map for fedora:hasParent and ldp:contains

---

.scripts/travis_setup.sh
.travis.yml
islandora/islandora.services.yml
islandora/src/EventGenerator/EventGenerator.php
islandora/src/EventGenerator/EventGeneratorInterface.php
islandora/tests/src/Kernel/EventGeneratorTest.php

Resolves https://github.com/Islandora-CLAW/CLAW/issues/445
How to test:
This is just a small piece for a bigger puzzle, and there's functional tests.  But if you want to verify by hand, I'd say devel is your best bet.  From http://localhost:8000/devel/php try 
```php
use Drupal\user\Entity\User;
use Drupal\islandora\Entity\FedoraResource;
use Drupal\islandora\EventGenerator\EventGenerator;
$user_id = \Drupal::currentUser()->id();
$user = User::load($user_id);
$entity = FedoraResource::load(4);
$eventGenerator = new EventGenerator();
$msg = $eventGenerator->generateCreateEvent($entity, $user);
dsm($msg);
```

AS2 Event Generator

---

.scripts/travis_setup.sh
.travis.yml

Resolves https://github.com/Islandora-CLAW/CLAW/issues/466
There's no way to test this right now other than Travis doesn't blow up.  The real test is https://github.com/Islandora-CLAW/CLAW/issues/467

Adding activemq to travis install

---

composer.json

This lets us keep minimum stability to stable but make exceptions for those that haven't had a stable release yet.
Part of Islandora-CLAW/CLAW#475

Adding @dev where appropriate

---

composer.json

Reverts Islandora-CLAW/islandora#28
We goofed.  The problem was elsewhere.

Revert "Adding @dev where appropriate"

---

composer.json

Resolves https://github.com/Islandora-CLAW/CLAW/issues/497
Removes [lines 16-19 from composer.json](https://github.com/islandora-CLAW/islandora/blob/8.x-1.x/composer.json#L16-L19) (repository/vcs)

Removes vcs entry from repository section of composer.json

---

config/install/rest.resource.entity.fedora_resource.yml

This is part of https://github.com/Islandora-CLAW/CLAW/issues/394

Adding rest resource for GET

---

config/install/rdf.mapping.fedora_resource_type.non_rdf_source.yml
config/install/rdf.mapping.fedora_resource_type.rdf_source.yml

Related to https://github.com/Islandora-CLAW/CLAW/issues/515
Change title -> name and uid -> user_id
Makes JSON-LD display the "Name" and "Authored By" field.

Correct RDF mapping

---

.travis.yml

Part of:
https://github.com/Islandora-CLAW/CLAW/issues/540
Make sure all repos use the same violations.

Don't style check MD and TXT Files

---

.travis.yml

**GitHub Issue**: none
Ignores markdown files on Drupal Coding standards.
See above.
Travis should pass.

ignore markdown

---

composer.json
config/install/field.storage.fedora_resource.field_obj.yml
config/install/field.storage.media.field_image.yml
islandora.info.yml
src/Plugin/RulesAction/Broadcaster.php
tests/src/Kernel/IslandoraKernelTestBase.php

**GitHub Issue**: Part of https://github.com/Islandora-CLAW/CLAW/issues/549
* Also part of https://github.com/Islandora-CLAW/CLAW/issues/490
* Blocks https://github.com/Islandora-CLAW/islandora_image/pull/11
Adds field storage for some fields that will be used across multiple bundles.
All config, all the time.
You should test https://github.com/Islandora-CLAW/islandora_image/pull/11 after merging this.  This is its prerequisite.

First pass at image bundles

---

config/install/rules.reaction.broadcast_media_create_event.yml
config/install/rules.reaction.broadcast_media_delete_event.yml
config/install/rules.reaction.broadcast_media_update_event.yml
islandora.module
src/EventGenerator/EventGenerator.php

**GitHub Issue**: Islandora-CLAW/CLAW#624
Updates reaction rules to take advantage of new routes in Alpaca.  Also adds an "attachment" section to the AS2 events that are generated for Media entities.  Registers iana as a namespace.
See Islandora-CLAW/CLAW#624
@ruebot @Islandora-CLAW/committers

Updates Reaction Rules for Media

---

src/EventGenerator/EventGenerator.php

**GitHub Issue**: None
Makes TravisCI happy.
Make sure TravisCI turns green.
@dannylamb

Sorry TravisCI, I'm the WORST.

---

.travis.yml

Islandora is crashy in Travis
Uses php without a memory limit to allow more memory to composer.

Fix OOM composer errors

---

composer.json

**GitHub Issue**: Part of https://github.com/Islandora-CLAW/CLAW/issues/950
Stops pulling HEAD for chullo
Here's an easy one @Islandora-CLAW/committers

Seting chullo dependency to an actual version and not dev-master

---

modules/islandora_audio/src/Plugin/Action/GenerateAudioDerivative.php

* https://github.com/Islandora-CLAW/CLAW/issues/930
* Changes the file name of the audio derivative file.
Tag (@ mention) interested parties or, if unsure, @Islandora-CLAW/committers

specific service file path format is needed!

---

src/EventSubscriber/NodeLinkHeaderSubscriber.php

* Other Relevant Links (Google Groups discussion, related pull requests,
Release pull requests, etc.)
A brief description of what the intended result of the PR will be and/or what
problem it solves.
A in-depth description of the changes made by this PR. Technical details and
possible side effects.
* Changes x feature to such that y
* Added x
* Removed y
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
(ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?
A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what …

Fix typos.

---

src/Flysystem/Fedora.php

**GitHub Issue**: [Islandora-CLAW/CLAW/issues/1030](https://github.com/Islandora-CLAW/CLAW/issues/1030)
Supersedes #118 (Thanks to @whikloj for [the idea for this new approach](https://logs.woh.ca/islandora/2019-02-27#501593;)!)
Related (but completely independent) PR: #116 for increasing JWT expiry times.
Modifies the Guzzle client handler to generate a new JWT token for every request.
* Replaced addHeader function with addJWT.
* Modified the create function to use the new addJWT function (which now generates the token) in the HandlerStack instead of generating the token and passing it through addHeader.
* Add the debug setting to Chullo FedoraApi class. Add `$options['debug'] = TRUE;` [about here](https://github.com/Islandora-CLAW/chullo/blob/master/src/FedoraApi.php#L76).
* Start a …

New JWT for each Flysystem request: Issue-1030

---

src/Plugin/Condition/EntityBundle.php

**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1065
* Other Relevant Links: Goes with https://github.com/Islandora-CLAW/islandora_demo/pull/22
Adds Media to the EntityBundle condition so we can filter all the things by Media and their bundles. 
Pretty much just made an extra annotation in the Condition and made a one line change in the code that builds the drop down box.
Test using the instructions in https://github.com/Islandora-CLAW/islandora_demo/pull/22
@ajstanley @Islandora-CLAW/committers

Issue 1065

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
modules/islandora_audio/README.md
modules/islandora_image/README.md
modules/islandora_text_extraction/README.md
modules/islandora_video/README.md

Ran Aspell CLI spell checker
I used an Aspell "word list" based on the "word list" from the ISLE repo found
here...
https://raw.githubusercontent.com/Islandora-Collaboration-Group/ISLE/master/.aspell.en.pws
Cleans up some misspellings, as far as I could tell.
Nothing.
Please eyeball my changes to see if I made a mistake. My apologies in advance.

Ran Aspell CLI spell checker

---

src/EventSubscriber/LinkHeaderSubscriber.php
src/EventSubscriber/NodeLinkHeaderSubscriber.php
src/Plugin/ContextReaction/JsonldTypeAlterReaction.php

**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1290
Replaces instances of string 'field_external_uri' with constant EXTERNAL_URI_FIELD.
Create Repository Items and check the watchdog log.

Issue 1290 fix
