islandora.links.menu.yml, islandora.links.task.yml, src/Entity/FedoraResource.php
Addresses https://github.com/Islandora-CLAW/CLAW/issues/418.
To test this pull:
- After pulling down the code, do a `drupal cache:rebuild all`
- Go to `admin/content`, you should see a tab for 'Fedora Resources'
- Click on the tab, and you should see a listing of the FedoraResource entities on your site, with operations to manage them.
=> Moving collection route to admin/content

src/Entity/FedoraResource.php
Addresses https://github.com/Islandora-CLAW/CLAW/issues/419.  See issue for testing instructions.
Turns out ContentEntityBase does a lookup based on the annotations to determine if it should make tables upon module install for an entity.  The revision tables require a 'revision' entity_key get made.  Adding 'translatable' ensures the data tables get made as well.
If you pull down the code with git, you're defining a revision entity_key that does not exist yet.  Your database will go kaboom.  I've done it twice today because of this.  Just a heads up.
=> Generated tables now

config/install/islandora.settings.yml, src/Form/IslandoraSettingsForm.php
Resolves https://github.com/Islandora-CLAW/CLAW/issues/431
Adds two new fields to the Islandora settings `http://localhost:8000/admin/config/islandora/core`
1. Fedora REST Endpoint
2. Fedora Indexing Queue Name
It also adds default values to the `config/install/islandora.settings.yml` file.
1. Install this PR in your Drupal 8.2.2 installation (if you already have the Islandora module installed, Uninstall it before you checkout this PR branch. Then reinstall the module.)
2. Browse to `http://<your host and port>/admin/config/islandora/core` 
3. Ensure you see **4** fields. 
4. Ensure they have default values
5. Ensure that you can edit and save those values and they persist if you leave the page and return.
=> Add new configuration settings

islandora_collection/config/install/field.field.fedora_resource.collection.field_description.yml, islandora_collection/config/install/field.storage.fedora_resource.field_description.yml
This is a PR for [#443](https://github.com/Islandora-CLAW/CLAW/issues/441).
What does this Pull Request do?
This PR changes the islandora_collection description field from text_with_summary to plain text.  
How should this be tested?
Install the module, export the field config and ensure that the description is plain text.
=> change description field to plain text

islandora/config/install/core.entity_view_mode.fedora_resource.teaser.yml
Addresses issue [Islandora-CLAW/CLAW#447](https://github.com/Islandora-CLAW/CLAW/issues/447), tested by exporting and importing again, and enabling view mode to Non-RDF source and RDF source.
=> add fedora resource teaser config schema for issue #447

islandora/src/Entity/FedoraResource.php
Resolves https://github.com/Islandora-CLAW/CLAW/issues/443
How to test:
First create a Fedora Resource (Content -> Fedora Resource -> Add Fedora Resource) 
**DON'T** set a parent.
Save the new Fedora Resource.
Create a second Fedora Resource and set this parent as the first Fedora Resource you created.
Save the new Fedora Resource.
View the Fedora Resource List (Content -> Fedora Resource), each Fedora Resource lists itself as it's own parent.
ie.
Checkout this PR, perform cache rebuild (`drupal cache:rebuild all` at drupal root folder), refresh the Fedora Resource List. The parents should be correct.
=> Correctly get parent

islandora/config/install/rdf.mapping.fedora_resource_type.non_rdf_source.yml
Resolves https://github.com/Islandora-CLAW/CLAW/issues/444
How to test:
First create a Fedora Resource of type **Non RDF Source** (Content -> Fedora Resource -> Add Fedora Resource)
Save the new Fedora Resource.
View the JSON-LD serialization by adding `?_format=jsonld` to the URL. You'll only see `@id` and `@type`
ie.
```
{"@graph":[{"@id":"http:\/\/localhost:8000\/fedora_resource\/6?_format=jsonld","@type":["http:\/\/schema.org\/Thing","http:\/\/www.w3.org\/ns\/ldp#RDFSource","http:\/\/www.w3.org\/ns\/ldp#Container"]}
```
Next checkout this PR branch. Install the included in the file `islandora/config/install/rdf.mapping.fedora_resource_type.non_rdf_source.yml` as a single item configuration and reload the the JSON-LD serialization of the Fedora Resource and see lots more information. …
=> Add default RDF mapping for NonRdfSource 

.scripts/line_endings.sh, .scripts/php56.ini, .scripts/travis_setup.sh, .travis.yml, README.md
The way were we installing Drupal for travis before was differnt from
how we installed it in the vagrant box. It required manually adding
dependancies for libraries. This should install all the dependancies
using composer automatically.
Came up on this pull request:
https://github.com/Islandora-CLAW/islandora/pull/38
Figured I should break it out to another pull since it got larger then 
I intended it to be.
=> Change how we setup travis to use composer to install all dependencies

.travis.yml
TravisCi provides the $TRAVIS_COMMIT environment variable which I was
using to get composer to install the correct version. However it appears
that under some circumstances travis does not set this variable to the
correct commit hash, which can cause our builds to fail. This avoids
using that variable all together to avoid that problem.
Related to: 
https://github.com/Islandora-CLAW/islandora/pull/38
https://github.com/Islandora-CLAW/CLAW/issues/540
=> Fix issue with travis running force pushed commits

src/Entity/FedoraResource.php, src/FedoraResourceInterface.php, tests/src/Kernel/DeleteFedoraResourceWithParentsTest.php, tests/src/Kernel/FedoraResourceParentTest.php
Resolves https://github.com/Islandora-CLAW/CLAW/issues/512
Add remove fedora_has_parent function.
Add query to get all inbound references.
Remove fedora_has_parent if the parent is deleted
Edit: Totally forgot
Without PR
1. Create a Fedora Resource
2. Create a second Fedora Resource and set the Has Parent field to the first.
3. Delete the parent Fedora Resource
4. Enjoy broken website
With PR
1. Repeat above 1-3
2. Worky-worky
This adds a `removeParent()` function to the `FedoraResourceInterface` as our `setParent()` requires an `EntityTypeInterface` argument and we use `NULL` to remove the value. 
It also adds a overridden `postDelete()` function which performs a query for all `fedora_resource` entities that have a `fedora_has_parent` field with the delete entities ID.
It then removes …
=> Clean up parents on resource deletion

.travis.yml
Removed php 5.5
**GitHub Issue**: (#560)
Remove php 5.5 from travis
Removed php 5.5
Try building with php 5.5 
No additional notes
@ruebot
=> issue-560: Updated travis.yml removed php 5.5

src/Plugin/RulesAction/Broadcaster.php, tests/src/Kernel/BroadcasterTest.php
**GitHub Issue**: Islandora-CLAW/CLAW#556
Updates the conditional to check if there's a JWT token to adhere to PHP's ridiculous truthiness.
I changed a direct `NULL` comparison to `empty()`.  This way if JWT configuration is invalid, you'll at least get a flash message and a log entry.
Delete your Key or Secret configuration and then perform a CRUD operation on a FedoraResource entity.  You should see an error message and a watchdog log entry.
=> PHP has a odd notion of truth

composer.json
Will be required once https://github.com/Islandora-CLAW/jsonld/pull/18 is merged.
=> Required once https://github.com/Islandora-CLAW/jsonld/pull/18 is merged

.travis.yml, composer.json
Part of:
https://github.com/Islandora-CLAW/CLAW/issues/594
Updates the Islandora `composer.json` to install the dev version of rules that contains the commits needed to run rules on 8.3.x. This is a first step in running Islandora against D8.3.
Not too much has changed in rules, except for the updates to make things work in D8.3, so this should be okay, as long as the Islandora tests pass. 
=> Update to use dev branch of rules

config/install/rules.reaction.broadcast_create_event.yml, config/install/rules.reaction.broadcast_delete_event.yml, config/install/rules.reaction.broadcast_update_event.yml, islandora.info.yml, tests/src/Kernel/IslandoraKernelTestBase.php
**GitHub Issue**: Part of Islandora-CLAW/CLAW#597
* Other Relevant Links 
Blocks an upcoming PR on Alpaca.
Updates configuration to point to new queues by default for fcrepo indexing.
Updated yaml.
* Uninstall islandora and its dependent modules
* `git pull` in this code
* Re-install islandora and its dependent modules
* Clear the drupal cache
* Go to the rules config and look up the `broadcast_*_event` rules.  They should be pointing to separate queues for each type of operation.  That is, `broadcast_create_event` should have `islandora-indexing-fcrepo-create` as one of its recipients.  `broadcast_update_event` should have `islandora-indexing-fcrepo-update` and `broadcast_delete_event` should have `islandora-indexing-fcrepo-delete` as recipients.
There's a pending PR on Alpaca that will …
=> Updating rules to publish events to new routes

islandora.install
**GitHub Issue**: None
Adds a `hook_install` which is a copy of @dannylamb's `hook_modules_installed`.
I did this.
1. `vagrant destroy`
2. `git pull` (to make sure I was up-to-date)
3. edit `../scripts/drupal.sh` at line 91 below
```
##
```
and above
```
$DRUSH_CMD en -y islandora
$DRUSH_CMD en -y islandora_collection
$DRUSH_CMD en -y islandora_image
```
I added
```
cd "$DRUPAL_HOME/web/modules/contrib"
rm -rf islandora
git clone https://github.com/whikloj/islandora-1.git --branch install-patch islandora
```
4. do `vagrant up`
5. When vagrant is finished, login and go to **Admin -> Configuration -> REST**
Beside **Content** you should see `jsonld` under `format` and `jwt_auth` under `Authentication`.
=> Add hook_install for rest configuration

islandora.module
* https://github.com/Islandora-CLAW/CLAW/issues/680
If a drupal content type has "field_memberof" field pointing to islandora_collection entities, then it will add the url to those entities as link header using the hook_node_view_alter.  
* Get the PR
* Create an islandora image node with field_memberof pointing to an existing collection
* Issue a `curl -I` request to the newly created node and get the header info
* Verify that the link info is included in the header, similar to below:
```
$ curl -I http://localhost:8000/node/2
HTTP/1.1 200 OK
---
Link: <http://localhost:8000/node/1>; rel='collection', <http://localhost:8000/node/3>; rel='collection'
Link: </node/2>; rel="canonical"
Link: </node/2>; rel="shortlink"
Link: </node/2>; rel="revision"
Content-Type: …
```
=> Expose parent collection as link header

config/schema/islandora.schema.yml, src/Plugin/Condition/IsReferencedMedia.php, tests/src/Functional/IsReferencedMediaTest.php
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/795
Adds a Condition that can be used with the Context UI module to filter Media based on what type of node is referncing them and what field is being used to do so. 
* An IsReferencedMedia Condition plugin
* Functional tests
* Updated schema.yml for the new Condition
- Uninstall `islandora`: https://gist.github.com/whikloj/614fa21d7145b09197fd1e8513dd2f41
- `cd /var/www/html/drupal/web/modules/contrib/islandora`
- `sudo git remote add danny https://github.com/dannylamb/islandora.git`
- `sudo git fetch danny`
- `sudo git checkout media-bundle-condition`
- `drush en islandora`
- `drush en context_ui`
Now that it's all set up, you can take it for a test drive.  I did this by making an Action that dsm's some text to the …
=> Referenced Media Condition

README.md, islandora.routing.yml, islandora.services.yml, src/Controller/MediaSourceController.php, src/MediaSource/MediaSourceService.php, tests/src/Functional/AddMediaToNodeTest.php, tests/src/Functional/MediaSourceControllerTest.php, tests/src/Functional/MediaSourceUpdateTest.php
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/796, depends on https://github.com/Islandora-Devops/claw-playbook/pull/57
Adds a route that lets users add new Media to Nodes by issuing POST requests.
A new controller method and custom access check. The route is located at `node/{node}/media/{field}/add/{bundle}`. There's tests to assert the following behaviours:
- It returns 404 if none of the route parameters exist in Drupal.
- It returns 403 if you do not have permissions to update the Node nor create a Media entity.
- It requires a request body, returning 400 if missing.
- It expects a `Content-Disposition` header of the form `attachment; filename="your_filename_with_extension"`, returning 400 if missing.
- It expects a `Content-Type` header, returning 400 if …
=> Add binary to node

islandora.module, src/ContextReaction/NormalizerAlterReaction.php, src/Plugin/ContextReaction/MappingUriPredicateReaction.php, tests/src/Functional/MappingUriPredicateReactionTest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/768
~Depends on~ https://github.com/Islandora-CLAW/jsonld/pull/24
Actually this just uses the hook from jsonld, not sure if anything bad happens if this is merged first.
Creates a reaction to alter the JSON-LD and add the entity id using a configurable predicate.
NormalizerAlterReaction is an abstract class to base reactions that alter the jsonld on.
MappingUriPredicateReaction extends the new above abstract class.
We call the new `hook_jsonld_alter_normalized_array` from jsonld and call any reactions that are a subclass of the `NormalizerAlterReaction` and they can edit the jsonld normalized array before it is encoded and returned.
* Does this change add any new …
=> Use Context to allow altering the normalized JSON-LD

islandora.services.yml, src/EventSubscriber/LinkHeaderSubscriber.php, src/EventSubscriber/MediaLinkHeaderSubscriber.php, src/EventSubscriber/NodeLinkHeaderSubscriber.php, tests/src/Functional/IslandoraFunctionalTestBase.php, tests/src/Functional/MediaLinkHeaderTest.php, tests/src/Functional/MediaSourceUpdateTest.php, tests/src/Functional/RelatedLinkHeaderTest.php
~Depends on: #71~ 
Ready to go
---
Replaces/copies from: https://github.com/Islandora-CLAW/islandora/pull/70
Part of: https://github.com/Islandora-CLAW/CLAW/issues/721
Uses event subscriber to add a `describes` and `edit-media` link header when viewing a media entity.
To test pull this PR. Create an islandora_image with one file. Then perform a `GET` or `HEAD` request for the media entity URI.
ie. 
```
> curl -I -u admin:islandora "http://localhost:8000/media/1?_format=jsonld"
HTTP/1.1 200 OK
Date: Mon, 15 Jan 2018 22:36:34 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Powered-By: PHP/7.0.22-0ubuntu0.16.04.1
Cache-Control: must-revalidate, no-cache, private
Link: <http://localhost:8000/media/add>; rel="https://drupal.org/link-relations/add-page"
Link: <http://localhost:8000/media/add/tn>; …
```
=> Add headers to media entities

README.md, islandora.module
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/813
Removes a previous attempt at forcing configuration, and instead provides
installation instructions through the README.
* Less cruft
* More docs
Read the doc updates?  The weird code I removed is pointless now that there's documentation.
=> No longer forcing REST config, README updates

islandora.services.yml, src/EventSubscriber/LinkHeaderSubscriber.php, src/EventSubscriber/MediaLinkHeaderSubscriber.php, src/EventSubscriber/NodeLinkHeaderSubscriber.php, tests/src/Functional/IslandoraFunctionalTestBase.php, tests/src/Functional/MappingUriPredicateReactionTest.php, tests/src/Functional/MediaLinkHeaderTest.php, tests/src/Functional/MediaSourceUpdateTest.php, tests/src/Functional/NodeLinkHeaderTest.php
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/717
Adds `rel=alternate type=mimetype` link headers to GET and HEAD requests, advertising our REST endpoints and what formats are enabled.
- Code to add those headers
- Updated tests
- Make a node
- Perform a HEAD request against its canonical URL (note we're doing this as anonymous)
```bash
ubuntu@claw:/var/www/html/drupal/web/modules/contrib/islandora$ curl -I http://localhost:8000/node/1
HTTP/1.1 200 OK
Date: Mon, 12 Mar 2018 14:48:50 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Powered-By: PHP/7.0.25-0ubuntu0.16.04.1
Cache-Control: must-revalidate, no-cache, private
Link: <http://localhost:8000/node/1?_format=jsonld>; rel="alternate"; type="application/ld+json"
Link: <http://localhost:8000/node/1?_format=json>; …
```
=> Meta link headers

src/EventSubscriber/LinkHeaderSubscriber.php
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/852
Adds an extra step of checks to not blow up when viewing content tagged with terms that have no external uri.
- Make a new taxonomy term, but don't give it an external uri.
- Make a new node and tag it with that term.
- Try and visit the term... KABOOM
```
ubuntu@claw:/var/www/html/drupal/web/modules/contrib/islandora/src$ curl -I localhost:8000/node/1
HTTP/1.0 500 500 Service unavailable (with message)
Date: Fri, 22 Jun 2018 02:50:02 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Powered-By: PHP/7.0.30-0ubuntu0.16.04.1
Cache-Control: no-cache, private
Connection: close
Content-Type: text/html; charset=UTF-8
```
- Apply this PR
- `drupal cr all`
- Now go and visit.  The term's internal URI should be used in the link header …
=> Fixing WSOD when term has no uri

modules/islandora_demo_feature/config/install/context.context.repository_content.yml
**GitHub Issue**: Resolves Islandora-CLAW/CLAW#853
Removes and unneccessary condition in the "All Repository Content" context, which was blocking form submission.
Less config.
First, confirm the old behaviour:
- Make a new content type
- Go to the Context UI and edit the "All Repository Content" context.
- Try to select your new content type in the checkbox for 'Node Bundle'
- You should be prevented from submitting the form.
Then confirm the fix:
- Pull in this PR
- Re-import the `islandora_demo_feature` feature
- Go to the Context UI and edit the "All Repository Content" context.
- Try to select your new content type in the checkbox for 'Node Bundle'
- You should be allowed to submit the form now.
You'll notice that the "Node Has Term" condition is gone from the list.  It had a required …
=> Removing unneccessary node_has_term condition

modules/islandora_core_feature/config/install/migrate_plus.migration.islandora_tags.yml, modules/islandora_demo_feature/config/install/migrate_plus.migration.islandora_demo_tags.yml
**GitHub Issue**: Islandora-CLAW/CLAW/issues/861
Changes the migration config for tags.csv to use a relative path.
A relative path for tags.csv
+ setup a new Drupal site; preferably one that doesn't use '/var/www/html/drupal/' which is part of the old hard-coded path. _Note: you don't need the whole CLAW to test this, just a vanilla Drupal works for the purposes of this test. I used a stock drupalvm site._
+ import the islandora core modules and feature
+ Run the islandora_tags migration
+ migration should run successfully with the new relative path.
=> make csv path relative

src/IslandoraUtils.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/900
Check that the retrieved parent is an object before trying to do a `getValue()` on it.
=> Check for the parent before we getValue

src/EventGenerator/EmitEvent.php
**GitHub Issue**: Islandora-CLAW/CLAW#846
* Islandora-CLAW/islandora_image#25
Catches exceptions when generating events so there's no more WSODing.
A try/catch block with some logging and dsm'ing.
Pull in this code.  Pull in Islandora-CLAW/islandora_image#25.  Clear your cache.  Try to generate an image derivative from a source that does not exist (e.g. you have no preservation master, and request a source file). You should get a dsm and a log entry that have the exception message in it. No WSOD.
Easy one to test @manez @Islandora-CLAW/committers
=> Catching exceptions when generating events to get published on the queue

src/Flysystem/Adapter/FedoraAdapter.php, tests/src/Kernel/FedoraAdapterTest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/908
After a delete it does a `HEAD` to the URL and if it gets a `410 Gone` response, it checks for a `Link` header with a `rel="hasTombstone"`.
It then tries to delete that tombstone.
This is very Fedora Community Implementation specific. But should not impact alternate implementations.
* Does this change require documentation to be updated? maybe
Before this PR files were created as entities in the database even if they weren't persisted to Fedora.
You could
1. go to Add Media
1. Upload a file
1. In …
=> Delete tombstone if it exists

.travis.yml, islandora.module
**GitHub Issue**: Resolves Islandora-CLAW/CLAW#931 in the sense core block placement is no longer busted.  
But deeper issues remain w/r/t the core block placement ui.  See https://www.drupal.org/node/2284687
Alters our custom `Condition` plugins out of the core block placement UI.  They shouldn't be there and are breaking core block placement.  This puts it back to the way a vanilla D8 would look.
If you want to do sophisticated block placement by arbitrary criteria, you'll need to use the Context UI at `/admin/structure/context`.
A `form_alter` and some `unset`s.
- Reproduce bug as per Islandora-CLAW/CLAW#931
- Pull down this code
- `drush cr`
- Go place a new block in Sidebar Second and see it appears.  Core block placement should be back to normal. …
=> Fixes core block placement: Issue 931

islandora.module
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/969
* Other Relevant Links (Google Groups discussion, related pull requests,
Release pull requests, etc.)
Limits changing the view mode to the current node only
A in-depth description of the changes made by this PR. Technical details and
possible side effects.
* Changes x feature to such that y
* Added x
* Removed y
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
(ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?
To test this create a collection and tag it with openseadragon.  Add some image objects to this collection and note that when viewing the …
=> only change view mode for the current node

modules/islandora_image/src/Plugin/Action/GenerateImageDerivative.php, modules/islandora_video/src/Plugin/Action/GenerateVideoDerivative.php, src/Plugin/Action/AbstractGenerateDerivative.php, tests/src/Functional/FormDisplayAlterReactionTest.php
Resolves: https://github.com/Islandora-CLAW/CLAW/issues/986
To allow for Image and Video events to share code we (I) tried to use the source media's bundle. But this causes problems when your source media is one type but the derivative should be another.
This PR adds a configuration option (Derivative media type) to the Action to set the destination media type which is used in the file_upload_uri when putting a new File into Drupal.
Before the PR, adding a Tiff as a File and you would end up with no derivatives …
=> Make derivative Drupal media type configurable

drush.services.yml, src/Commands/IslandoraCommands.php
**GitHub Issue**: ([Issue 988](https://github.com/Islandora-CLAW/CLAW/issues/988))
Adds a userid option to Drush migrate:import command that uses the Drupal Account Switch to perform the migration as the specified user.
* Changes Drush migrate:import feature to such that is has a userid option
* Does this change require documentation to be updated? Probably.
(ie. Regeneration activity, etc.)? No, but it helps get us ready for Fedora 5.
* Could this change impact execution of existing code? No.
Currently, performing a migration using Drush migrate will technically work, but all the derivative creations will fail. 
So:
1. roll back the migration `drush -l …
=> Add userid option to migrate:import

src/Plugin/Condition/EntityBundle.php, src/Plugin/ContextReaction/JsonldTypeAlterReaction.php
**GitHub Issue**: [Issue 889](https://github.com/Islandora-CLAW/CLAW/issues/889)
Adds a new Condition Plugin allowing users to specify which bundles apply. Adds a new Reaction Plugin to alter the JSON-LD's `@type` attribute based on the predicate values in the configured field.
* Added
- EntityBundle Condition Plugin
- JsonldTypeAlterReaction Reaction Plugin
* Does this change require documentation to be updated? maybe?
* Does this change add any new dependencies? no.
(ie. Regeneration activity, etc.)? Only if you want it.
* Could this change impact execution of existing code? no.
- Apply this PR to the islandora module.
- Clear cache (otherwise the new condition and reaction plugins won't show up in your …
=> Allow JSON-LD @Type to be configurable based on a specified Content Entity field

modules/islandora_audio/LICENSE, modules/islandora_audio/README.md, modules/islandora_audio/config/schema/islandora_audio.info.yml, modules/islandora_audio/islandora_audio.info.yml, modules/islandora_audio/islandora_audio.module, modules/islandora_audio/src/Plugin/Action/GenerateAudioDerivative.php, modules/islandora_audio/tests/fixtures/test_file.txt, modules/islandora_audio/tests/src/Functional/GenerateAudioDerivativeTest.php
* https://github.com/Islandora-CLAW/CLAW/issues/930
Similar to video derivative plugin, this PR adds an audio derivative plugin.  
* islandora_audio sub module
* Get this PR
* Go to modules and install the sub module: `/admin/modules`
* Go to actions: `/admin/config/system/actions`.  you should see a `Generate a audio derivative` option
Would be good if you can review and see if video and audio can be abstracted into a single module.  It seems easier to keep them separate.
@whikloj @MarcusBarnes  @dannylamb 
=> islandora_audio plugin module

src/Controller/ManageMembersController.php
https://github.com/Islandora-CLAW/CLAW/issues/1028
* Other Relevant Links (Google Groups discussion, related pull requests,
Release pull requests, etc.)
Fix path passed in URL query that Prepopulate module uses to inject parent Repository Item into node or media entity form, e.g. from `?edit%5Bfield_member_of%5D=1` to `?edit%5Bfield_member_of%5D%5Bwidget%5D%5B0%5D%5Btarget_id%5D=1`
A brief description of what the intended result of the PR will be and/or what
problem it solves.
Per #1028, add repository item, click members tab, add member, confirm that Member of field is correctly populated.
A in-depth description of the changes made by this PR. Technical details and
possible side effects.
* Changes x feature to such that y
* Added x
* Removed y
* Does this change …
=> #1028 Fix member of, media of prepopulate via URL query

src/MediaSource/MediaSourceService.php
**GitHub Issue**: Part of https://github.com/Islandora-CLAW/CLAW/issues/978
Adds an `fclose` to the REST endpoint that adds Media to files via PUT.
You should no longer hit the file descriptors wall as per https://github.com/Islandora-CLAW/CLAW/issues/978
@seth-shaw-unlv
=> Missing a fclose :S

src/EventSubscriber/JwtEventSubscriber.php, src/Form/IslandoraSettingsForm.php
**GitHub Issue**: /Islandora-CLAW/CLAW/issues/1030
See also the IRC conversations linked from the issue.
This PR amends the Islandora core setting form to include the option of setting a JWT expiration time (default is currently hard-coded as '+2 hour') and updates the JwtEventSubscription to use the setting (if available, the default '+2 hour' if not).
* Changes JwtEventSubscriber feature to such that the expiration is pulled from configuration.
* Added JWT Setting to Islandora core settings form.
- Add the debug setting to Chullo FedoraApi class. Add `$options['debug'] = TRUE;` [about here](https://github.com/Islandora-CLAW/chullo/blob/master/src/FedoraApi.php#L76).
- Start a migration of any sort that pushes to Fedora (you can limit it to just one item for debugging purposes).
- You …
=> Make JWT Expiry configurable - Issue 1030

src/Plugin/Action/EmitFileEvent.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1014
Fixes URIs persisted to Gemini like `http://localhost:8080/fcrepo/rest//islandora_2_MODS.xml` so that they don't contain double forward slashes (`//`).
Within the `src/Plugin/Action/EmitFileEvent.php` class, checks to see if the incoming URI for the file contains a redundant `/`, and if so, removes it.
Since this error manifested itself in a migration from a 7.x instance, you will need one of those to test this fix. 
1. Install the Migrate 7.x CLAW module (in /var/www/html/drupal, run `composer require islandora/migrate_7x_claw`)
1. Configure your migration as described in https://github.com/Islandora-Devops/migrate_7x_claw.
1. Enable the migration modules by running `drush en islandora_migrate_7x_claw_feature`.
1. …
=> Work on https://github.com/Islandora-CLAW/CLAW/issues/1014.

composer.json, config/schema/islandora.schema.yml, islandora.module, islandora.services.yml, src/Form/IslandoraSettingsForm.php, src/GeminiClientFactory.php, src/GeminiLookup.php, tests/src/Functional/IslandoraFunctionalTestBase.php, tests/src/Functional/IslandoraSettingsFormTest.php, tests/src/Kernel/EventGeneratorTest.php, tests/src/Kernel/GeminiClientFactoryTest.php, tests/src/Kernel/GeminiLookupTest.php, tests/src/Kernel/JwtEventSubscriberTest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/881
Creates a pseudo field to display the linked URI from the Gemini database on the Drupal resource.
Create two new services, one is a GeminiClient (with factory) and one does the lookup from an entity.
Alters the Islandora Core Settings to allow for a Gemini URI (with some simple validation) and to select which node, media or taxononomy_terms can have the field displayed.
Uses two hooks in `islandora.module` to define the new fields and build them.
* Does this change require documentation to be updated? Maybe
* Does this change add any new dependencies? yes, change from chullo to crayfish-commons
* Could …
=> Display Fedora URI in Drupal

config/schema/islandora.schema.yml, src/Plugin/Field/FieldFormatter/IslandoraImageFormatter.php, tests/src/Functional/IslandoraImageFormatterTest.php
**GitHub Issue**: An attempt to resolve https://github.com/Islandora-CLAW/CLAW/issues/1032
Adds a new Image field formatter that renders image as links to the Node's content and not the Media.  This means you can make a view that queries for all media with X Properties that belong to a node with Y Properties, etc... And have those images lead to the _node_ when clicked.  This means we can make teaser mode lead to the full content of the link when the user clicks on the thumbnail in it.  It also means we can make galleries or slideshows using views super easily.  If you're capable of contextual filters and relationships in views, you can do _a ton_ of things.
An image field formatter that interprets the "Content" selection for link settings as pointing to the node that's the …
=> Slideshow image formatter

islandora.services.yml, src/GeminiLookup.php, tests/src/Kernel/GeminiLookupTest.php
**GitHub Issue**: 
- Resolves https://github.com/Islandora-CLAW/CLAW/issues/881
- Resolves https://github.com/Islandora-CLAW/CLAW/issues/1109
- Follow up to https://github.com/Islandora-CLAW/islandora/pull/124
Adds the Fedora Uri pseudo-field to Media.
Looks up media in addition to other entity types in the GeminiLookup class.  This is done by issuing a HEAD request against the binary in Fedora to find it's `rel="describedby"` link header.
- Pull down this PR
- Clear your cache
- You should now see the Fedora Uri pseudo-field on Media entities
=> Media Fedora Uri Pseudo-Fields

islandora.module
**GitHub Issue**: n/a
Related to: Islandora-CLAW/CLAW#881
Previous work assumed a "full" view mode, but if you enable the OpenSeadragon viewer you end up in the "open_seadragon" view mode and the field is not displayed.
I couldn't just remove the if statement as when you view a "repository item" you hit the `hook_entity_view` 3 times, once for the node, once for the user and once for the media (service file image). So you'd end up with more than one Fedora URI displayed.
This PR gets the current "entity" from the route and ensures that we only display the Fedora URI for that item entity. So node on the node page, media on the media page, etc.
* Does this change add any new dependencies?  no
* Does this change require any other …
=> Allow multiple view modes

migrate/tags.csv
**GitHub Issue**: 
- Part of https://github.com/Islandora-CLAW/CLAW/issues/1111
- Required by https://github.com/Islandora-CLAW/islandora_demo/pull/28
Gives PDFs their own model so that they can be differentiated from other binaries during derivative generation.
A taxonomy term for schema:DigitalDocument
https://github.com/Islandora-Devops/claw-playbook/pull/105
=> Adding model for Digital Documents (e.g. pdf)

composer.json, src/ContextReaction/NormalizerAlterReaction.php, src/Plugin/ContextReaction/JsonldTypeAlterReaction.php, src/Plugin/ContextReaction/MappingUriPredicateReaction.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/887
Goes with
- https://github.com/Islandora-CLAW/jsonld/pull/33
- https://github.com/Islandora-CLAW/Crayfish/pull/66
Supersedes: https://github.com/Islandora-CLAW/islandora/pull/133
**This is the same code as https://github.com/Islandora-CLAW/islandora/pull/133, just on the Foundation's repo so that it can be tested with claw-playbook**
Forces our jsonld alters to respect the `jsonld` module's configuration for stripping out `?_format=jsonld` from urls.
The jsonld module's configuration is injected into our base class for altering jsonld using context.  There's a helper function implemented in the base class that generates the appropriate url to use when searching the jsonld graph for the entity in question.
See …
=>  Respecting jsonld module configuration for ?_format=jsonld

composer.json, islandora.info.yml, modules/islandora_core_feature/config/install/webform.webform.islandora_upload.yml, src/Plugin/WebformHandler/IslandoraUploadWebformHandler.php, tests/src/Kernel/IslandoraKernelTestBase.php, tests/src/Kernel/IslandoraUploadWebformHandlerTest.php
**GitHub Issue**: Resolves Islandora-CLAW/CLAW#919
Uses webform to construct a quick upload form that can be embedded in a page as a block or as a field on a node.  This will allow users to customize the block placement/positioning and create custom submission pages.
A webform, its handler plugin, and some tests.  Functionality is purely additive.  Nothing else should be affected.
- `composer require drupal/webform`
- Pull in this PR
- `drush fim -y islandora_core_feature`
- `drush cr`
- Visit `http://localhost:8000/form/islandora-upload` and fill out the form.  Upload a file.  Submit it.
- You should get redirected to the edit form of the node you just made.  You can confirm it has the correct model.  If you click on its media tab, you should see a Media for the file you uploaded with …
=> Simpler upload form to link media and node in one shot

src/Flysystem/Fedora.php
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/985
Forces flysystem downloads from Fedora to be language neutral.  This prevents the language prefix from getting jammed into the url.
An overridden getExternalUrl() method that forces the language to be Undefined (und).
- Make a second language and set one to default 
- Go visit a media that you put in Fedora, and its file's url should have the language prefix in it, e.g. `http://localhost:8000/en/_flysystem/fedora/2019-05/blah.jpg`
- Pull in this PR
- Clear the cache
- Go visit the same media, and now the language prefix should be gone, e.g. `http://localhost:8000/_flysystem/fedora/2019-05/blah.jpg`
@kanasznagyzoltan @rangel35 @DonRichards @Islandora-CLAW/committers
=> Forcing flysystem downloads to be language neutral

src/Plugin/ContextReaction/MappingUriPredicateReaction.php, tests/src/Functional/MappingUriPredicateReactionTest.php
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/662
Requires https://github.com/Islandora-CLAW/islandora_demo/pull/29 and https://github.com/Islandora-CLAW/Crayfish/pull/68
Swaps media and file urls when altering jsonld with `MappingUriPredicateReaction`.
One line change and a test to confirm its behaviour.
- Make a media and view it's ?_format=jsonld route, you should see something like this (edited for brevity):
```json
{
"@graph":[
{
"@id":"http://localhost:8000/media/1",
"@type":[
"http://pcdm.org/models#File",
"http://pcdm.org/use#OriginalFile"
],
...
"http://schema.org/sameAs":[
{
"@value":"http://localhost:8000/_flysystem/fedora/2019-05/Flemming-Magic.jpg"
}
]
},
...
]
}
```
- Pull changes from https://github.com/Islandora-CLAW/islandora_demo/pull/29 into …
=> Swapping file and media urls in jsonld

config/install/islandora.settings.yml, islandora.module, src/Form/IslandoraSettingsForm.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1129
Instead of embedded defaults this creates a default configuration object, which allows us to modify the settings in the claw-playbook post-install.yml
Replace defaults in code and checks (as there will now be some value provided)
I made an islandora_demo branch to call this branch. So to test, pull a clean claw-playbook. 
Then make this change
```
diff --git a/inventory/vagrant/group_vars/webserver/drupal.yml …
```
=> Set default settings

src/Plugin/ContextReaction/MappingUriPredicateReaction.php, tests/src/Functional/MappingUriPredicateReactionTest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1131
Swaps the `@value` for a `@id` in the JSON-LD of the mappingUriPredicate Content reaction.
1. Create Repository Item without this PR.
1. View the `?_format=jsonld` of your resource, notice the 
```
"http:\/\/schema.org\/sameAs":[{"@value":"http:\/\/localhost:8000\/node\/1"}]
```
1. Pull in this PR, clear cache and view `?_format=jsonld` again
```
"http:\/\/schema.org\/sameAs":[{"@id":"http:\/\/localhost:8000\/node\/1"}]
``` …
=> Switch @value to @id

islandora.services.yml, src/EventGenerator/EventGenerator.php, src/Flysystem/Fedora.php, tests/src/Kernel/EventGeneratorTest.php, tests/src/Kernel/FedoraPluginTest.php, tests/src/Kernel/IslandoraKernelTestBase.php
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/1127
The same fix for https://github.com/Islandora-CLAW/islandora/pull/137, but applied to urls getting put into messages on their way to the queue.  This may also partially resolve issues arising from https://github.com/Islandora-CLAW/CLAW/issues/1095.  At least this same pattern will have to be repeated (read: put into utility function and just call that).
Forcing URLs to be language neutral.  Plus some minor refactoring to properly inject the language manager.
Confirm Original Behaviour:
- Add a language to turn on content translation (I added French)
- Make a node
- Click its translate tab
- Add a translation (again, French for me)
- Save the translation
- Go check out the node in the triplestore and fedora, …
=> Fixes content translation

.travis.yml
**GitHub Issue**: n/a
Relies on https://github.com/Islandora-CLAW/CLAW/pull/1146
To make enabling testing on sub-modules easier, as in https://github.com/Islandora-CLAW/islandora/pull/132
Calls the scripts added to the main CLAW `.scripts` directory.
This will fail Travis until https://github.com/Islandora-CLAW/CLAW/pull/1146 is merged, then restarting the travis build should pass.
=> use common testing scripts

.travis.yml, modules/islandora_breadcrumbs/config/install/islandora.breadcrumbs.yml, modules/islandora_breadcrumbs/config/schema/islandora_breadcrumbs.schema.yml, modules/islandora_breadcrumbs/islandora_breadcrumbs.info.yml, modules/islandora_breadcrumbs/islandora_breadcrumbs.services.yml, modules/islandora_breadcrumbs/src/IslandoraBreadcrumbBuilder.php, modules/islandora_breadcrumbs/tests/src/Functional/BreadcrumbsTest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1141
Provides an islandora_breadcrumb submodule. The breadcrumbs are created by following the field_member_of chain from the current node until it runs out of links.
* Added the islandora_breadcrumbs submodule.
* Does this change require documentation to be updated? We could add some....
* Could this change impact execution of existing code? No, it is completely optional and only impacts other breadcrumb settings you may have.
* Make a collection
* Make a sub-collection belonging to the first collection (repeat as often as you would like)
* Make an item …
=> Breadcrumbs sub-module

islandora.services.yml, modules/islandora_audio/tests/src/Functional/GenerateAudioDerivativeTest.php, modules/islandora_breadcrumbs/tests/src/Functional/BreadcrumbsTest.php, modules/islandora_image/tests/src/Functional/GenerateImageDerivativeTest.php, modules/islandora_video/tests/src/Functional/GenerateVideoDerivativeTest.php, src/ContextReaction/NormalizerAlterReaction.php, src/Controller/MediaSourceController.php, src/EventGenerator/EventGenerator.php, src/EventSubscriber/LinkHeaderSubscriber.php, src/EventSubscriber/MediaLinkHeaderSubscriber.php, src/EventSubscriber/NodeLinkHeaderSubscriber.php, src/Flysystem/Adapter/FedoraAdapter.php, src/Flysystem/Fedora.php, src/IslandoraUtils.php, src/Plugin/Action/AbstractGenerateDerivative.php, src/Plugin/ContextReaction/MappingUriPredicateReaction.php, src/PresetReaction/PresetReaction.php, tests/src/Functional/GenerateDerivativeTestBase.php, tests/src/Functional/IslandoraFunctionalTestBase.php, tests/src/Kernel/EventGeneratorTest.php, tests/src/Kernel/GeminiClientFactoryTest.php, tests/src/Kernel/GeminiLookupTest.php
**GitHub Issues**
Part of 
- https://github.com/Islandora-CLAW/CLAW/issues/1110
- https://github.com/Islandora-CLAW/CLAW/issues/1095
- https://github.com/Islandora-CLAW/CLAW/issues/1144
Refactors the code so every time we request a URL from an entity, it goes through a utility function for consistency.  This makes us Drupal 8.7 compatible, as well as solves our outstanding issue with url aliases for nodes.
Three new utility functions for generating URLs in `IslandoraUtils`.  Then everything else is just the dependency injection boilerplate to get `IslandoraUtils` into all the other classes.
Also had to touch up tests so that they set the checkbox for keeping media urls as in 8.6.
claw-playbook PR pending
=> Refactoring URL generation into util functions

modules/islandora_core_feature/config/install/field.storage.media.field_media_use.yml
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1142
Changes the cardinality of field_media_use from '1' to ''-1' allowing a media to have multiple uses (e.g. OriginalFile AND ServiceFile). 
* Changes `islandora/modules/islandora_core_feature/config/install/field.storage.media.field_media_use.yml`'s cardinality from '1' to '-1' 
* Does this change require documentation to be updated? Maybe...
(ie. Regeneration activity, etc.)? No! `\0/`
* Could this change impact execution of existing code? No. Everything miraculously still works.
* Apply the PR (to a site with content or an empty site, doesn't matter which).
* Import the change to …
=> Change field_media_use cardinality

config/schema/islandora.schema.yml, islandora.module, src/Plugin/Condition/MediaHasMimetype.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1138
Adds a Context Condition to detect the MIME type of the media being displayed with a node or as a media.
A new Condition class file. The Condition is also in the list of Conditions to hide from the Block placement GUI.
The boring way:
1. Check out this branch and `drush cr`.
1. Create a new Context using the "Media Has Mime type" condition.
1. Configure the condition to use the 'image/png' Mime type.
1. Use "Theme" as the Reaction, and choose the Bartik theme.
1. Go to an image object whose Original File has the specified Mime type.
1. The theme should have changed to Bartik.
1. Go to an image object whose Original File is not a PNG. The theme should be the default.
1. Add another Mime type to the condition's …
=> Adds a Context Condition to detect the MIME type of the media

config/schema/islandora.schema.yml, islandora.module, src/Plugin/Condition/NodeHasParent.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1170
Adds a Context Condition that tests a node's parent, which can be either a collection object or not.
Adds the new Condition, and also adds its ID to the list in `islandora.module` that excludes this condition from the Block placement UI.
1. Check out this branch and `drush cr`.
1. Create a new Context using the "Node has parent" condition.
1. In the Parent Node field, enter the name of a collection.
1. Choose the name of the field that contains the parent reference (probably `field_member_of`)
1. Use "Theme" as the Reaction, and choose the Bartik theme.
1. Go to an object that is not in the collection you named in your Conext. The theme should remain the default.
1. Now go to an object that is in the collection you named …
=> Adds a Context Condition that tests a node's parent

config/schema/islandora.schema.yml, islandora.module, src/Plugin/Condition/NodeHadNamespace.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1185
Adds a Context Condition that tests the Islandora 7.x namespace in `field_pid` (or any other configured field).
Adds the new Condition, and also adds its ID to the list in `islandora.module` that excludes this condition from the Block placement UI.
1. Populate the PID field of an object with 'islandora:100'
1. Check out this branch and `drush cr`.
1. Create a new Context using the "Node had 7.x namespace" condition.
1. In the Islandora 7.x Namespaces field, enter 'islandora:`
1. Choose the name of the field that contains the PID (probably `field_pid`)
1. Use "Theme" as the Reaction, and choose the Bartik theme.
1. Go to the object you edited in the first step. You should see the Bartik theme.
1. Visit some other node. …
=> Create a Context Condition that detects the namespace in the PID field

src/Plugin/Condition/NodeHadNamespace.php
**GitHub Issue**: (https://github.com/Islandora-CLAW/CLAW/issues/1199)
Replaces reference to `field_pid` with the configured field name.
* Does this change require documentation to be updated? No
* Does this change add any new dependencies?  No
(ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? Yes, but to the expected behavior.
1. Populate the Rights field of an object with 'islandora:100'
1. Check out this branch and `drush cr`.
1. Create a new Context using the "Node had 7.x namespace" condition.
1. In the Islandora 7.x Namespaces field, enter 'islandora:`
1. Choose `field_rights` in the list of available fields.
1. Use "Theme" as the Reaction, and choose the Bartik …
=> NodeHadNamespace condition uses hard-coded field, should use configured field

modules/islandora_core_feature/config/install/field.field.media.audio.field_media_use.yml, modules/islandora_core_feature/config/install/field.field.media.file.field_media_use.yml, modules/islandora_core_feature/config/install/field.field.media.image.field_media_use.yml, modules/islandora_core_feature/config/install/field.field.media.video.field_media_use.yml
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1186
* Other Relevant Links: old PR made to the wrong repo: https://github.com/Islandora-CLAW/islandora_defaults/pull/3
Adds a bit of help text to the Media Use field to explain which selection generates derivatives, and how to find out more.
`Defined by Portland Common Data Model: Use Extension https://pcdm.org/2015/05/12/use. 'Original File' will trigger creation of derivatives.`
Pull in the changes and do a feature import (`drush fim -y islandora_core_feature`), then go try to add new Media in each of the existing types, verifying that the help text appears.
@seth-shaw-unlv @mjordan
=> Add in-form help text for Media Use field on the four standard media types

modules/islandora_core_feature/config/install/field.storage.node.field_display_hints.yml
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1211
Makes Display Hints a single-option field so users can't turn on two different displays at once for a single object (because it doesn't work when they do).
Literally just a -1 becoming a 1 in the right place. But this does also add "N/A" as a default option, which I think Drupal requires for fields with limits? I didn't add it. It just showed up when the cardinality was changed. 
* Does this change require documentation to be updated? Some screenshots may need updating. 
* Could this change impact execution of existing code? I don't think so? The addition …
=> Issue #1211 Update field.storage.node.field_display_hints.yml

src/Plugin/Condition/NodeIsPublished.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1214
Adds a new Condition plugin to check if a Node is published or not.
* Added a "Node Is Published" condition plugin.
* Does this change require documentation to be updated? No.
* Could this change impact execution of existing code? Not unless you want it to.
1. Apply the PR
1. Clear cache
1. Add the 'Node is Published' condition to repository content condition (http://localhost:8000/admin/structure/context/repository_content) and check 'Require all conditions' checkbox: 
1. Create a new islandora_object node BUT don't select 'Published'. The node's page …
=> Node Is Published Condition

.travis.yml, modules/islandora_breadcrumbs/islandora_breadcrumbs.services.yml, modules/islandora_breadcrumbs/src/IslandoraBreadcrumbBuilder.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1238
Uses the getRawParameter instead of getParameter for loading the node in question. getParameter has inconsistent behavior, providing a node object when viewing the node page but only providing the node id as a string when viewing a tab, so we use getRawParameter which _always_ gives the node id as a string.
* Changes BreadcrumbBuilder::applies to use getRawParameter instead of getParameter.
* Does this change require documentation to be updated? No.
* Could this change impact execution of existing code? No.
- Enable the islandora_breadcrumbs module.
- …
=> Fix Breadcrumb error when viewing node tab: Issue 1238

src/Controller/ManageMediaController.php, src/EventSubscriber/AdminViewsRouteSubscriber.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1057
Alters the route for the views to add a permission requirement and a custom function to check for 2 expected fields indicating its an Islandora object.
1. Get an islandora 8 instance running.
1. Create a Repository Item (assuming you are using the islandora_defaults module)
1. See the Media and Members tab when viewing the node as the Administrator
1. Create a Basic Page
1. See the Media and Members tab when viewing the node as the …
=> Hide media and members tabs on non-Islandora objects.

migrate/tags.csv
3 new tags to cover standard books and periodicals/newspapers 
and the sub Page model
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1265
* Other Relevant Links (Google Groups discussion, related pull requests,
Release pull requests, etc.)
Adds islandora models for paged content
A in-depth description of the changes made by this PR. Technical details and
possible side effects.
* Changes x feature to such that y
* Added x
* Removed y
* Does this change require documentation to be updated? 
* Does this change add any new dependencies? 
(ie. Regeneration activity, etc.)? 
* Could this change impact execution of existing code?
A description of what steps someone could take to:
import tags
ingest …
=> adding tags for paged content

modules/islandora_iiif/src/Plugin/views/style/IIIFManifest.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1263
Adds additional properties to IIIF manifest required by Presentation API
Adds a label to the manifest, and adds width/height to the canvas and image. Also adds the mimetype of the image. Since Drupal treats TIFFs differently than normal images, the height/width is calculated special for TIFFs using PHP's [getimagesize](https://www.php.net/manual/en/function.getimagesize.php)
- Enable islandora_iiif submodule
- Add your IIIF Server URL (the same one you'd have configured for OSD) at /admin/config/islandora/iiif
- Import this "test" // "demo" view: https://gist.github.com/dannylamb/c90686957d3d5599f49f2cab02f045d4
- Access a node that has an image referencing the node via field_media_of e.g. /node/1
- Add "iiif-manifest" …
=> IIIF Presentation API Validator

src/Plugin/Condition/NodeHasTerm.php, tests/src/Functional/NodeHasTermTest.php
**GitHub Issue**: Part of https://github.com/Islandora-CLAW/CLAW/issues/932
Allows multiple terms to be used in the `NodeHasTerm`, `MediaHasTerm`, and `ParentNodeForMediaHasTerm` conditions.
A new `evaluate()` function in `NodeHasTerm`, which flows through to the other two condition plugins that extend it.
Plus I wrote a test.
Try out the Condition in context.  Make it look for two terms.  Save the condition.  Then see if it works with nodes that do and do not have the terms.
@Islandora-CLAW/committers @elizoller
=> Allowing NodeHasTerm to check for multiple tags using AND logic

islandora.links.action.yml, modules/islandora_core_feature/config/install/views.view.manage_members.yml, modules/islandora_core_feature/config/install/views.view.members.yml
**GitHub Issue**: Islandora-CLAW/CLAW/issues/1272
As discussed in [the Islandora 8 Tech Call on September 11, 2019](https://github.com/Islandora-CLAW/CLAW/wiki/September-11%2C-2019).
Simply updates "Members" to "Children" in the front-end UI.
* Changes manage_members view to such that it displays "Children" in the menu tab.
* Changes the "Add members" link on the "Members" (now "Children") tab/page to display "Add child".
* Changes members view to such that it titles the block "Children".
* Does this change require documentation to be updated? _Probably_
(ie. Regeneration activity, etc.)? _Routes cache should be cleared to make the "Add members" button to …
=> Change 'Members' in UI to 'Children'

islandora.module, modules/islandora_core_feature/config/install/field.storage.node.field_weight.yml, modules/islandora_text_extraction/LICENSE, modules/islandora_text_extraction/README.md, modules/islandora_text_extraction/islandora_text_extraction.info.yml, modules/islandora_text_extraction/islandora_text_extraction.install, modules/islandora_text_extraction/islandora_text_extraction.module, modules/islandora_text_extraction/src/Plugin/Action/GenerateOCRDerivative.php, modules/islandora_text_extraction/src/Plugin/Field/FieldFormatter/OcrTextFormatter.php, modules/islandora_text_extraction/tests/src/Functional/LoadTest.php, modules/islandora_text_extraction_defaults/config/install/core.entity_form_display.media.extracted_text.default.yml, modules/islandora_text_extraction_defaults/config/install/core.entity_view_display.media.extracted_text.default.yml, modules/islandora_text_extraction_defaults/config/install/field.field.media.extracted_text.field_edited_text.yml, modules/islandora_text_extraction_defaults/config/install/field.field.media.extracted_text.field_media_file.yml, modules/islandora_text_extraction_defaults/config/install/field.field.media.extracted_text.field_media_of.yml, modules/islandora_text_extraction_defaults/config/install/field.field.media.extracted_text.field_media_use.yml, modules/islandora_text_extraction_defaults/config/install/field.field.media.extracted_text.field_mime_type.yml, modules/islandora_text_extraction_defaults/config/install/field.storage.media.field_edited_text.yml, modules/islandora_text_extraction_defaults/config/install/language.content_settings.media.extracted_text.yml, modules/islandora_text_extraction_defaults/config/install/media.type.extracted_text.yml, modules/islandora_text_extraction_defaults/config/install/system.action.get_ocr_from_image.yml, modules/islandora_text_extraction_defaults/islandora_text_extraction_defaults.features.yml, modules/islandora_text_extraction_defaults/islandora_text_extraction_defaults.info.yml, src/IslandoraUtils.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/933
* Other Relevant Links:
- https://github.com/Islandora-CLAW/Crayfish/pull/77
PR to add `islandora_text_extraction` from roblib as a submodule.  Config has been extracted out into a corresponding feature, `islandora_text_extraction_defaults`.
Test PR to come
@Islandora-CLAW/committers @dbernstein @ajstanley
=> Text extraction

modules/islandora_core_feature/config/install/field.storage.node.field_weight.yml
**GitHub Issue**: https://github.com/Islandora-CLAW/islandora_defaults/pull/7#issuecomment-533149938
Slack: https://islandora.slack.com/archives/CM5PPAV28/p1568903292154300
Fixes Travis failing on `drush fim -y islandora_core_feature` due to unmet dependency for field_permissions.
* Removed field.storage.node.field_weight.yml dependency on field_permissions
* Does this change require documentation to be updated? No
* Could this change impact execution of existing code? No.
- Merge PR
- Travis is happy again.
None of the other configs in islandora_core_feature require field_permissions; this shouldn't either.
@dannylamb
=> remove field_permissions dependency

islandora.links.action.yml, islandora.module, islandora.views.inc, modules/islandora_core_feature/config/install/views.view.reorder_children.yml, src/EventSubscriber/AdminViewsRouteSubscriber.php, src/Plugin/views/field/IntegerWeightSelector.php, tests/modules/integer_weight_test_views/integer_weight_test_views.info.yml, tests/modules/integer_weight_test_views/test_views/views.view.test_integer_weight.yml, tests/src/FunctionalJavascript/IntegerWeightTest.php
**GitHub Issue**: Islandora-CLAW/CLAW/issues/1262
Test with Islandora-CLAW/islandora_defaults/pull/9
This PR ports the weight module's drag-n-drop code to work with our integer-based weight field (instead of using the weight module's weight field type). Yes, it means more code to support, _but_ that sacrifice means that we can have null-value weights (no weight value at all) for those repository items that don't need them and force positive values (which makes more sense to human-viewers of the resulting RDF).
* Added a new "Integer weight selector" with associated implementations of  hook_views_data_alter() and hook_preprocess_views_view_table().
* Does this change require documentation to be updated? We should add some documentation.
* …
=> Integer-based weight drag-n-drop (Issue 1262)

islandora.module, src/Plugin/Condition/MediaIsIslandoraMedia.php, src/Plugin/Condition/NodeIsIslandoraObject.php
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1270
* Other Relevant Links: https://github.com/Islandora-CLAW/islandora/pull/160#commitcomment-34979924
Adds 1) a Context Condition that checks to see if the current node has two fields: `field_model` and   `field_member_of` and 2) a Context Condition that checks to see if the current media has two fields, 'field_media_use' and 'field_media_of'.
* src/Plugin/Condition/NodeIsIslandoraObject.php
* src/Plugin/Condition/MediaIsIslandoraMedia.php
1. Check out this PR.
1. Clear your cache (e.g. `drush cr`)
1. Create a new Context at `http://localhost:8000/admin/structure/context`
1. For a condition, use "Node is an Islandora object."
1. For a reaction, use "Blocks" (you could use any, but making a block show up is a good visual …
=> Work on #1270.
